# Generated by Django 5.2.17 on 2026-08-29 20:00

import apps.events.models
import apps.events.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('published', 'Publicado'), ('archived', 'Arquivado')], default='draft', max_length=10)),
                ('schedule_status', models.CharField(choices=[('scheduled', 'Agendado'), ('postponed', 'Adiado'), ('canceled', 'Cancelado')], default='scheduled', max_length=10, verbose_name='situação')),
                ('event_type', models.CharField(blank=True, choices=[('lecture', 'Palestra'), ('seminar', 'Seminário'), ('workshop', 'Workshop'), ('course', 'Curso'), ('defense', 'Defesa'), ('conference', 'Conferência'), ('meetup', 'Encontro'), ('other', 'Outro')], max_length=20, verbose_name='tipo')),
                ('modality', models.CharField(blank=True, choices=[('in_person', 'Presencial'), ('online', 'Online'), ('hybrid', 'Híbrido')], max_length=10, verbose_name='modalidade')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='data de início')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='data de término')),
                ('is_all_day', models.BooleanField(default=False, verbose_name='evento de dia inteiro')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='hora de início')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='hora de término')),
                ('cover', models.ImageField(blank=True, upload_to=apps.events.models.event_cover_upload_to, validators=[apps.events.validators.validate_event_cover], verbose_name='imagem de divulgação')),
                ('cover_credit', models.CharField(blank=True, max_length=200, verbose_name='crédito da imagem')),
                ('online_url', models.URLField(blank=True, max_length=500, verbose_name='URL de acesso online')),
                ('registration_url', models.URLField(blank=True, max_length=500, verbose_name='URL externa de inscrição')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='ordem de exibição')),
                ('published_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='publicado em')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events_created', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events_updated', to=settings.AUTH_USER_MODEL, verbose_name='atualizado por')),
            ],
            options={
                'verbose_name': 'evento',
                'verbose_name_plural': 'eventos',
                'ordering': ('start_date', 'start_time', 'display_order', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='EventTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('pt-br', 'Português (Brasil)'), ('en', 'English')], max_length=5, verbose_name='idioma')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='título')),
                ('slug', models.SlugField(blank=True, max_length=220, null=True)),
                ('summary', models.TextField(blank=True, max_length=400, verbose_name='resumo')),
                ('body_html', models.TextField(blank=True, verbose_name='descrição')),
                ('location_name', models.CharField(blank=True, max_length=200, verbose_name='nome do local')),
                ('location_address', models.CharField(blank=True, max_length=300, verbose_name='endereço')),
                ('cover_alt_text', models.CharField(blank=True, max_length=250, verbose_name='texto alternativo da imagem')),
                ('seo_title', models.CharField(blank=True, max_length=70, verbose_name='título para SEO')),
                ('seo_description', models.CharField(blank=True, max_length=160, verbose_name='descrição para SEO')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='events.event')),
            ],
            options={
                'verbose_name': 'tradução',
                'verbose_name_plural': 'traduções',
                'ordering': ('language',),
            },
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__isnull', True), ('start_date__isnull', True), ('end_date__gte', models.F('start_date')), _connector='OR'), name='event_end_date_not_before_start'),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.CheckConstraint(condition=models.Q(('is_all_day', False), models.Q(('start_time__isnull', True), ('end_time__isnull', True)), _connector='OR'), name='all_day_event_has_no_times'),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'published'), _negated=True), models.Q(('start_date__isnull', False), ('end_date__isnull', False), models.Q(('event_type', ''), _negated=True), models.Q(('modality', ''), _negated=True)), _connector='OR'), name='published_event_has_core_schedule'),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('modality__in', ('online', 'hybrid')), ('status', 'published'), _negated=True), models.Q(('online_url', ''), _negated=True), _connector='OR'), name='published_online_event_has_url'),
        ),
        migrations.AddConstraint(
            model_name='eventtranslation',
            constraint=models.UniqueConstraint(fields=('event', 'language'), name='unique_event_translation_language'),
        ),
        migrations.AddConstraint(
            model_name='eventtranslation',
            constraint=models.UniqueConstraint(condition=models.Q(('slug__isnull', False)), fields=('language', 'slug'), name='unique_event_translation_slug_per_language'),
        ),
    ]
