# Generated by Django 5.2.17 on 2026-08-29 16:47

import apps.projects.models
import apps.projects.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('researchers', '0004_remove_translation_role_and_photo_alt_text'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('published', 'Publicado'), ('archived', 'Arquivado')], default='draft', max_length=10)),
                ('situation', models.CharField(choices=[('planned', 'Planejado'), ('ongoing', 'Em andamento'), ('completed', 'Concluído')], default='planned', max_length=10, verbose_name='situação')),
                ('cover', models.ImageField(blank=True, upload_to=apps.projects.models.project_cover_upload_to, validators=[apps.projects.validators.validate_project_cover], verbose_name='imagem de capa')),
                ('cover_credit', models.CharField(blank=True, max_length=200, verbose_name='crédito da imagem')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='data de início')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='data de término')),
                ('funding', models.CharField(blank=True, max_length=300, verbose_name='financiamento')),
                ('partners', models.TextField(blank=True, help_text='Informe um parceiro por linha.', verbose_name='parceiros')),
                ('website_url', models.URLField(blank=True, max_length=500, verbose_name='site do projeto')),
                ('repository_url', models.URLField(blank=True, max_length=500, verbose_name='repositório')),
                ('is_featured', models.BooleanField(default=False, verbose_name='destaque')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='ordem de exibição')),
                ('published_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='publicado em')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('coordinator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='coordinated_projects', to='researchers.researcher', verbose_name='coordenador')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects_created', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects_updated', to=settings.AUTH_USER_MODEL, verbose_name='atualizado por')),
            ],
            options={
                'verbose_name': 'projeto',
                'verbose_name_plural': 'projetos',
                'ordering': (models.Case(models.When(situation='ongoing', then=models.Value(0)), models.When(situation='planned', then=models.Value(1)), models.When(situation='completed', then=models.Value(2)), default=models.Value(3), output_field=models.IntegerField()), 'display_order', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='ProjectTeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_memberships', to='projects.project')),
                ('researcher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_memberships', to='researchers.researcher', verbose_name='pesquisador')),
            ],
            options={
                'verbose_name': 'integrante da equipe',
                'verbose_name_plural': 'integrantes da equipe',
            },
        ),
        migrations.AddField(
            model_name='project',
            name='team',
            field=models.ManyToManyField(blank=True, related_name='projects', through='projects.ProjectTeamMember', to='researchers.researcher', verbose_name='equipe'),
        ),
        migrations.CreateModel(
            name='ProjectTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('pt-br', 'Português (Brasil)'), ('en', 'English')], max_length=5, verbose_name='idioma')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='título')),
                ('slug', models.SlugField(blank=True, max_length=220, null=True)),
                ('summary', models.TextField(blank=True, max_length=400, verbose_name='resumo')),
                ('body_html', models.TextField(blank=True, verbose_name='descrição')),
                ('seo_title', models.CharField(blank=True, max_length=70, verbose_name='título para SEO')),
                ('seo_description', models.CharField(blank=True, max_length=160, verbose_name='descrição para SEO')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='projects.project')),
            ],
            options={
                'verbose_name': 'tradução',
                'verbose_name_plural': 'traduções',
                'ordering': ('language',),
            },
        ),
        migrations.AddConstraint(
            model_name='projectteammember',
            constraint=models.UniqueConstraint(fields=('project', 'researcher'), name='unique_project_team_member'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__isnull', True), ('start_date__isnull', True), ('end_date__gte', models.F('start_date')), _connector='OR'), name='project_end_not_before_start'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'published'), _negated=True), ('coordinator__isnull', False), _connector='OR'), name='published_project_has_coordinator'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'published'), _negated=True), ('start_date__isnull', False), _connector='OR'), name='published_project_has_start_date'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('situation', 'completed'), ('status', 'published'), _negated=True), ('end_date__isnull', False), _connector='OR'), name='completed_published_project_has_end'),
        ),
        migrations.AddConstraint(
            model_name='projecttranslation',
            constraint=models.UniqueConstraint(fields=('project', 'language'), name='unique_project_translation_language'),
        ),
        migrations.AddConstraint(
            model_name='projecttranslation',
            constraint=models.UniqueConstraint(condition=models.Q(('slug__isnull', False)), fields=('language', 'slug'), name='unique_project_translation_slug_per_language'),
        ),
    ]
