# Generated by Django 5.2.17 on 2026-08-29 03:10

import apps.news.models
import apps.news.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('published', 'Publicada'), ('archived', 'Arquivada')], default='draft', max_length=10)),
                ('cover', models.ImageField(blank=True, upload_to=apps.news.models.news_cover_upload_to, validators=[apps.news.validators.validate_news_cover], verbose_name='imagem de capa')),
                ('cover_credit', models.CharField(blank=True, max_length=200, verbose_name='crédito da imagem')),
                ('published_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='publicada em')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criada em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizada em')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news_created', to=settings.AUTH_USER_MODEL, verbose_name='criada por')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news_updated', to=settings.AUTH_USER_MODEL, verbose_name='atualizada por')),
            ],
            options={
                'verbose_name': 'notícia',
                'verbose_name_plural': 'notícias',
                'ordering': ('-published_at', '-pk'),
            },
        ),
        migrations.CreateModel(
            name='NewsTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('pt-br', 'Português (Brasil)'), ('en', 'English')], max_length=5, verbose_name='idioma')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='título')),
                ('slug', models.SlugField(blank=True, max_length=220, null=True)),
                ('summary', models.TextField(blank=True, max_length=400, verbose_name='resumo')),
                ('body_html', models.TextField(blank=True, verbose_name='conteúdo')),
                ('cover_alt_text', models.CharField(blank=True, max_length=200, verbose_name='texto alternativo da capa')),
                ('seo_title', models.CharField(blank=True, max_length=70, verbose_name='título para SEO')),
                ('seo_description', models.CharField(blank=True, max_length=160, verbose_name='descrição para SEO')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='news.news')),
            ],
            options={
                'verbose_name': 'tradução',
                'verbose_name_plural': 'traduções',
                'ordering': ('language',),
                'constraints': [models.UniqueConstraint(fields=('news', 'language'), name='unique_news_translation_language'), models.UniqueConstraint(condition=models.Q(('slug__isnull', False)), fields=('language', 'slug'), name='unique_news_translation_slug_per_language')],
            },
        ),
    ]
