# Generated by Django 5.2.17 on 2026-08-29 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newstranslation',
            name='cover_alt_text',
        ),
    ]
