# Generated by Django 5.2.17 on 2026-08-29 18:59

import apps.publications.models
import apps.publications.validators
import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('researchers', '0004_remove_translation_role_and_photo_alt_text'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('published', 'Publicado'), ('archived', 'Arquivado')], default='draft', max_length=10)),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1000)], verbose_name='ano')),
                ('venue', models.CharField(blank=True, max_length=300, verbose_name='periódico ou evento')),
                ('doi', models.CharField(blank=True, max_length=255, verbose_name='DOI')),
                ('external_url', models.URLField(blank=True, max_length=500, verbose_name='URL externa')),
                ('document', models.FileField(blank=True, upload_to=apps.publications.models.publication_file_upload_to, validators=[apps.publications.validators.validate_publication_file], verbose_name='arquivo PDF')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='ordem de exibição')),
                ('published_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='publicado em')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publications_created', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='publications', to='projects.project', verbose_name='projeto relacionado')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publications_updated', to=settings.AUTH_USER_MODEL, verbose_name='atualizado por')),
            ],
            options={
                'verbose_name': 'publicação',
                'verbose_name_plural': 'publicações',
                'ordering': ('-year', 'display_order', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='PublicationAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_name', models.CharField(blank=True, max_length=200, verbose_name='nome do autor externo')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='ordem')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_records', to='publications.publication')),
                ('researcher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='publication_authorships', to='researchers.researcher', verbose_name='pesquisador cadastrado')),
            ],
            options={
                'verbose_name': 'autor',
                'verbose_name_plural': 'autores',
                'ordering': ('display_order', 'pk'),
            },
        ),
        migrations.AddField(
            model_name='publication',
            name='authors',
            field=models.ManyToManyField(blank=True, related_name='publications', through='publications.PublicationAuthor', to='researchers.researcher', verbose_name='autores cadastrados'),
        ),
        migrations.CreateModel(
            name='PublicationTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('pt-br', 'Português (Brasil)'), ('en', 'English')], max_length=5, verbose_name='idioma')),
                ('title', models.CharField(blank=True, max_length=500, verbose_name='título')),
                ('abstract', models.TextField(blank=True, verbose_name='resumo')),
                ('seo_title', models.CharField(blank=True, max_length=70, verbose_name='título para SEO')),
                ('seo_description', models.CharField(blank=True, max_length=160, verbose_name='descrição para SEO')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='publications.publication')),
            ],
            options={
                'verbose_name': 'tradução',
                'verbose_name_plural': 'traduções',
                'ordering': ('language',),
            },
        ),
        migrations.AddConstraint(
            model_name='publicationauthor',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('external_name', ''), ('researcher__isnull', False)), models.Q(('researcher__isnull', True), models.Q(('external_name', ''), _negated=True)), _connector='OR'), name='publication_author_has_exactly_one_identity'),
        ),
        migrations.AddConstraint(
            model_name='publicationauthor',
            constraint=models.UniqueConstraint(condition=models.Q(('researcher__isnull', False)), fields=('publication', 'researcher'), name='unique_publication_researcher_author'),
        ),
        migrations.AddConstraint(
            model_name='publicationauthor',
            constraint=models.UniqueConstraint(fields=('publication', 'display_order'), name='unique_publication_author_order'),
        ),
        migrations.AddConstraint(
            model_name='publication',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('doi'), condition=models.Q(('doi', ''), _negated=True), name='unique_publication_doi_case_insensitive'),
        ),
        migrations.AddConstraint(
            model_name='publicationtranslation',
            constraint=models.UniqueConstraint(fields=('publication', 'language'), name='unique_publication_translation_language'),
        ),
    ]
