# Generated by Django 5.2.17 on 2026-08-29 19:39

import apps.publications.models
import apps.publications.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='cover',
            field=models.ImageField(blank=True, upload_to=apps.publications.models.publication_cover_upload_to, validators=[apps.publications.validators.validate_publication_cover], verbose_name='imagem de divulgação'),
        ),
        migrations.AddField(
            model_name='publication',
            name='cover_credit',
            field=models.CharField(blank=True, max_length=200, verbose_name='crédito da imagem'),
        ),
        migrations.AddField(
            model_name='publicationtranslation',
            name='cover_alt_text',
            field=models.CharField(blank=True, max_length=250, verbose_name='texto alternativo da imagem'),
        ),
    ]
