# Generated by Django 5.2.17 on 2026-08-30 13:49

import apps.courses.models
import apps.courses.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('published', 'Publicado'), ('archived', 'Arquivado')], default='draft', max_length=10)),
                ('course_type', models.CharField(blank=True, choices=[('channel', 'Canal'), ('course', 'Curso'), ('playlist', 'Playlist'), ('tutorial', 'Tutorial'), ('recorded_live', 'Live gravada'), ('other', 'Outro')], max_length=20, verbose_name='tipo')),
                ('external_url', models.URLField(blank=True, max_length=500, validators=[apps.courses.validators.validate_https_url], verbose_name='URL externa')),
                ('cover', models.ImageField(blank=True, upload_to=apps.courses.models.course_cover_upload_to, validators=[apps.courses.validators.validate_course_cover], verbose_name='imagem de divulgação')),
                ('cover_credit', models.CharField(blank=True, max_length=200, verbose_name='crédito da imagem')),
                ('is_featured', models.BooleanField(default=False, verbose_name='destaque na página inicial')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='ordem de exibição')),
                ('published_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='publicado em')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses_created', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses_updated', to=settings.AUTH_USER_MODEL, verbose_name='atualizado por')),
            ],
            options={
                'verbose_name': 'curso e tutorial',
                'verbose_name_plural': 'cursos e tutoriais',
                'ordering': ('-is_featured', 'display_order', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='CourseTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('pt-br', 'Português (Brasil)'), ('en', 'English')], max_length=5, verbose_name='idioma')),
                ('title', models.CharField(blank=True, max_length=300, verbose_name='título')),
                ('summary', models.TextField(blank=True, verbose_name='resumo')),
                ('cover_alt_text', models.CharField(blank=True, max_length=250, verbose_name='texto alternativo da imagem')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='courses.course')),
            ],
            options={
                'verbose_name': 'tradução',
                'verbose_name_plural': 'traduções',
                'ordering': ('language',),
            },
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.CheckConstraint(condition=models.Q(('external_url', ''), ('external_url__startswith', 'https://'), _connector='OR'), name='course_external_url_is_https'),
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'published'), _negated=True), models.Q(models.Q(('course_type', ''), _negated=True), models.Q(('external_url', ''), _negated=True)), _connector='OR'), name='published_course_has_type_and_url'),
        ),
        migrations.AddConstraint(
            model_name='coursetranslation',
            constraint=models.UniqueConstraint(fields=('course', 'language'), name='unique_course_translation_language'),
        ),
    ]
