# Generated by Django 5.2.17 on 2026-08-29 20:57

import apps.labcompap.models
import apps.labcompap.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('researchers', '0004_remove_translation_role_and_photo_alt_text'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LabCompApPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_key', models.CharField(default='labcompap', editable=False, max_length=20, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('published', 'Publicado'), ('archived', 'Arquivado')], default='draft', max_length=10)),
                ('acronym', models.CharField(default='LabCompAp', max_length=30, verbose_name='sigla')),
                ('institution', models.CharField(blank=True, max_length=200, verbose_name='instituição')),
                ('campus', models.CharField(blank=True, max_length=150)),
                ('founded_on', models.DateField(blank=True, null=True, verbose_name='data de criação')),
                ('street_address', models.CharField(blank=True, max_length=250, verbose_name='logradouro')),
                ('locality', models.CharField(blank=True, max_length=120, verbose_name='cidade')),
                ('region', models.CharField(blank=True, max_length=80, verbose_name='estado')),
                ('postal_code', models.CharField(blank=True, max_length=20, verbose_name='CEP')),
                ('country_code', models.CharField(default='BR', max_length=2, verbose_name='país')),
                ('pnipe_url', models.URLField(blank=True, max_length=500, verbose_name='página no PNIPE')),
                ('map_url', models.URLField(blank=True, max_length=1000, verbose_name='link do mapa')),
                ('public_email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail institucional')),
                ('phone', models.CharField(blank=True, max_length=40, verbose_name='telefone')),
                ('whatsapp_url', models.URLField(blank=True, max_length=500, verbose_name='WhatsApp')),
                ('website_url', models.URLField(blank=True, max_length=500, verbose_name='site externo')),
                ('published_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='publicado em')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('coordinator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='coordinated_labs', to='researchers.researcher', verbose_name='coordenador')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='labcompap_pages_created', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='labcompap_pages_updated', to=settings.AUTH_USER_MODEL, verbose_name='atualizado por')),
            ],
            options={
                'verbose_name': 'página do LabCompAp',
                'verbose_name_plural': 'página do LabCompAp',
            },
        ),
        migrations.CreateModel(
            name='LabGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='ordem de exibição')),
                ('image', models.ImageField(upload_to=apps.labcompap.models.labcompap_image_upload_to, validators=[apps.labcompap.validators.validate_labcompap_image], verbose_name='imagem')),
                ('credit', models.CharField(blank=True, max_length=200, verbose_name='crédito')),
                ('alt_text_pt_br', models.CharField(blank=True, max_length=250, verbose_name='texto alternativo (PT-BR)')),
                ('alt_text_en', models.CharField(blank=True, max_length=250, verbose_name='texto alternativo (EN)')),
                ('caption_pt_br', models.CharField(blank=True, max_length=250, verbose_name='legenda (PT-BR)')),
                ('caption_en', models.CharField(blank=True, max_length=250, verbose_name='legenda (EN)')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='labcompap.labcompappage')),
            ],
            options={
                'verbose_name': 'imagem da galeria',
                'verbose_name_plural': 'galeria',
                'ordering': ('display_order', 'pk'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LabHeroImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='ordem de exibição')),
                ('image', models.ImageField(upload_to=apps.labcompap.models.labcompap_image_upload_to, validators=[apps.labcompap.validators.validate_labcompap_image], verbose_name='imagem')),
                ('credit', models.CharField(blank=True, max_length=200, verbose_name='crédito')),
                ('alt_text_pt_br', models.CharField(blank=True, max_length=250, verbose_name='texto alternativo (PT-BR)')),
                ('alt_text_en', models.CharField(blank=True, max_length=250, verbose_name='texto alternativo (EN)')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hero_images', to='labcompap.labcompappage')),
            ],
            options={
                'verbose_name': 'imagem do hero',
                'verbose_name_plural': 'imagens do hero',
                'ordering': ('display_order', 'pk'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LabProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='ordem de exibição')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_memberships', to='labcompap.labcompappage')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_memberships', to='projects.project', verbose_name='projeto')),
            ],
            options={
                'verbose_name': 'projeto relacionado',
                'verbose_name_plural': 'projetos relacionados',
                'ordering': ('display_order', 'pk'),
            },
        ),
        migrations.AddField(
            model_name='labcompappage',
            name='projects',
            field=models.ManyToManyField(blank=True, related_name='labs', through='labcompap.LabProject', to='projects.project', verbose_name='projetos relacionados'),
        ),
        migrations.CreateModel(
            name='LabResearchArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='ordem de exibição')),
                ('icon', models.CharField(choices=[('dna', 'DNA'), ('brain', 'Inteligência'), ('cpu', 'Computação'), ('database', 'Dados'), ('sprout', 'Agrária')], default='cpu', max_length=20)),
                ('accent', models.CharField(choices=[('emerald', 'Verde'), ('amber', 'Âmbar'), ('cyan', 'Ciano')], default='emerald', max_length=10, verbose_name='cor')),
                ('title_pt_br', models.CharField(max_length=150, verbose_name='título (PT-BR)')),
                ('title_en', models.CharField(max_length=150, verbose_name='título (EN)')),
                ('description_pt_br', models.TextField(max_length=500, verbose_name='descrição (PT-BR)')),
                ('description_en', models.TextField(max_length=500, verbose_name='descrição (EN)')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_areas', to='labcompap.labcompappage')),
            ],
            options={
                'verbose_name': 'área de pesquisa',
                'verbose_name_plural': 'áreas de pesquisa',
                'ordering': ('display_order', 'pk'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LabTeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='ordem de exibição')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_memberships', to='labcompap.labcompappage')),
                ('researcher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lab_memberships', to='researchers.researcher', verbose_name='pesquisador')),
            ],
            options={
                'verbose_name': 'integrante da equipe',
                'verbose_name_plural': 'equipe',
                'ordering': ('display_order', 'researcher__full_name', 'pk'),
            },
        ),
        migrations.AddField(
            model_name='labcompappage',
            name='team',
            field=models.ManyToManyField(blank=True, related_name='labs', through='labcompap.LabTeamMember', to='researchers.researcher', verbose_name='equipe'),
        ),
        migrations.CreateModel(
            name='LabTechnique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='ordem de exibição')),
                ('category', models.CharField(choices=[('ai', 'IA / Machine Learning'), ('data', 'Ciência de Dados'), ('bio', 'Bioinformática')], max_length=10)),
                ('name_pt_br', models.CharField(max_length=180, verbose_name='nome (PT-BR)')),
                ('name_en', models.CharField(max_length=180, verbose_name='nome (EN)')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='techniques', to='labcompap.labcompappage')),
            ],
            options={
                'verbose_name': 'técnica',
                'verbose_name_plural': 'técnicas e competências',
                'ordering': ('display_order', 'pk'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LabCompApTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('pt-br', 'Português (Brasil)'), ('en', 'English')], max_length=5, verbose_name='idioma')),
                ('full_name', models.CharField(blank=True, max_length=200, verbose_name='nome completo')),
                ('tagline', models.CharField(blank=True, max_length=250, verbose_name='chamada')),
                ('summary', models.TextField(blank=True, max_length=500, verbose_name='resumo')),
                ('about_html', models.TextField(blank=True, verbose_name='sobre o laboratório')),
                ('areas_intro', models.CharField(blank=True, max_length=300, verbose_name='introdução das áreas')),
                ('techniques_intro', models.CharField(blank=True, max_length=300, verbose_name='introdução das técnicas')),
                ('equipment_intro', models.CharField(blank=True, max_length=300, verbose_name='introdução da infraestrutura')),
                ('gallery_intro', models.CharField(blank=True, max_length=300, verbose_name='introdução da galeria')),
                ('contact_intro', models.CharField(blank=True, max_length=300, verbose_name='introdução do contato')),
                ('seo_title', models.CharField(blank=True, max_length=70, verbose_name='título para SEO')),
                ('seo_description', models.CharField(blank=True, max_length=160, verbose_name='descrição para SEO')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='labcompap.labcompappage')),
            ],
            options={
                'verbose_name': 'tradução',
                'verbose_name_plural': 'traduções',
                'ordering': ('language',),
                'constraints': [models.UniqueConstraint(fields=('page', 'language'), name='unique_labcompap_translation_language')],
            },
        ),
        migrations.CreateModel(
            name='LabEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='ordem de exibição')),
                ('inventory_code', models.CharField(max_length=60, verbose_name='código')),
                ('name_pt_br', models.CharField(max_length=200, verbose_name='nome (PT-BR)')),
                ('name_en', models.CharField(max_length=200, verbose_name='nome (EN)')),
                ('brand', models.CharField(blank=True, max_length=120, verbose_name='marca')),
                ('model_name', models.CharField(blank=True, max_length=180, verbose_name='modelo')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to='labcompap.labcompappage')),
            ],
            options={
                'verbose_name': 'equipamento',
                'verbose_name_plural': 'equipamentos',
                'ordering': ('display_order', 'pk'),
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('page', 'inventory_code'), name='unique_labcompap_equipment_code')],
            },
        ),
        migrations.AddConstraint(
            model_name='labproject',
            constraint=models.UniqueConstraint(fields=('page', 'project'), name='unique_labcompap_project'),
        ),
        migrations.AddConstraint(
            model_name='labteammember',
            constraint=models.UniqueConstraint(fields=('page', 'researcher'), name='unique_labcompap_team_member'),
        ),
        migrations.AddConstraint(
            model_name='labcompappage',
            constraint=models.CheckConstraint(condition=models.Q(('site_key', 'labcompap')), name='labcompap_singleton_site_key'),
        ),
        migrations.AddConstraint(
            model_name='labcompappage',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'published'), _negated=True), models.Q(models.Q(('institution', ''), _negated=True), models.Q(('campus', ''), _negated=True), models.Q(('street_address', ''), _negated=True), models.Q(('locality', ''), _negated=True), models.Q(('region', ''), _negated=True)), _connector='OR'), name='published_labcompap_has_location'),
        ),
    ]
