# Generated by Django 5.2.17 on 2026-08-30 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labcompap', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labheroimage',
            name='page',
        ),
        migrations.RemoveConstraint(
            model_name='labcompappage',
            name='published_labcompap_has_location',
        ),
        migrations.RemoveField(
            model_name='labcompappage',
            name='acronym',
        ),
        migrations.RemoveField(
            model_name='labcompappage',
            name='campus',
        ),
        migrations.RemoveField(
            model_name='labcompappage',
            name='country_code',
        ),
        migrations.RemoveField(
            model_name='labcompappage',
            name='founded_on',
        ),
        migrations.RemoveField(
            model_name='labcompappage',
            name='institution',
        ),
        migrations.RemoveField(
            model_name='labcompappage',
            name='locality',
        ),
        migrations.RemoveField(
            model_name='labcompappage',
            name='pnipe_url',
        ),
        migrations.RemoveField(
            model_name='labcompappage',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='labcompappage',
            name='published_at',
        ),
        migrations.RemoveField(
            model_name='labcompappage',
            name='region',
        ),
        migrations.RemoveField(
            model_name='labcompappage',
            name='status',
        ),
        migrations.RemoveField(
            model_name='labcompappage',
            name='street_address',
        ),
        migrations.AlterField(
            model_name='labcompaptranslation',
            name='about_html',
            field=models.TextField(verbose_name='sobre o laboratório'),
        ),
        migrations.AlterField(
            model_name='labcompaptranslation',
            name='full_name',
            field=models.CharField(max_length=200, verbose_name='nome completo'),
        ),
        migrations.AlterField(
            model_name='labcompaptranslation',
            name='summary',
            field=models.TextField(max_length=500, verbose_name='resumo'),
        ),
        migrations.AlterField(
            model_name='labcompaptranslation',
            name='tagline',
            field=models.CharField(max_length=250, verbose_name='chamada'),
        ),
        migrations.DeleteModel(
            name='LabHeroImage',
        ),
    ]
