# Generated by Django 5.2.17 on 2026-08-30 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labcompap', '0002_remove_labheroimage_page_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LabTechnique',
        ),
    ]
