# Generated by Django 5.2.17 on 2026-08-30 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labcompap', '0003_delete_labtechnique'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labcompappage',
            name='projects',
        ),
        migrations.RemoveField(
            model_name='labresearcharea',
            name='page',
        ),
        migrations.RemoveField(
            model_name='labteammember',
            name='page',
        ),
        migrations.RemoveField(
            model_name='labteammember',
            name='researcher',
        ),
        migrations.RemoveField(
            model_name='labcompappage',
            name='team',
        ),
        migrations.RemoveField(
            model_name='labcompappage',
            name='coordinator',
        ),
        migrations.DeleteModel(
            name='LabProject',
        ),
        migrations.DeleteModel(
            name='LabResearchArea',
        ),
        migrations.DeleteModel(
            name='LabTeamMember',
        ),
    ]
