# Generated by Django 5.2.17 on 2026-08-30 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labcompap', '0004_remove_labcompappage_projects_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labcompappage',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='labcompappage',
            name='updated_by',
        ),
        migrations.RemoveConstraint(
            model_name='labequipment',
            name='unique_labcompap_equipment_code',
        ),
        migrations.RemoveField(
            model_name='labequipment',
            name='page',
        ),
        migrations.RemoveField(
            model_name='labgalleryimage',
            name='page',
        ),
        migrations.RemoveField(
            model_name='labcompaptranslation',
            name='page',
        ),
        migrations.AlterField(
            model_name='labequipment',
            name='inventory_code',
            field=models.CharField(max_length=60, unique=True, verbose_name='código'),
        ),
        migrations.DeleteModel(
            name='LabCompApPage',
        ),
        migrations.DeleteModel(
            name='LabCompApTranslation',
        ),
    ]
