# Generated by Django 5.2.17 on 2026-08-29

import apps.researchers.models
import apps.researchers.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Researcher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=200, verbose_name="nome completo")),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        upload_to=apps.researchers.models.researcher_photo_upload_to,
                        validators=[apps.researchers.validators.validate_researcher_photo],
                        verbose_name="foto",
                    ),
                ),
                (
                    "public_email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        verbose_name="e-mail institucional ou profissional",
                    ),
                ),
                (
                    "lattes_url",
                    models.URLField(blank=True, max_length=500, verbose_name="Currículo Lattes"),
                ),
                ("orcid_url", models.URLField(blank=True, max_length=500, verbose_name="ORCID")),
                (
                    "linkedin_url",
                    models.URLField(blank=True, max_length=500, verbose_name="LinkedIn"),
                ),
                ("is_active", models.BooleanField(default=False, verbose_name="ativo")),
                (
                    "display_order",
                    models.PositiveIntegerField(default=0, verbose_name="ordem de exibição"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="criado em")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="atualizado em")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="researchers_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="criado por",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="researchers_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="atualizado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "pesquisador",
                "verbose_name_plural": "pesquisadores",
                "ordering": ("display_order", "full_name", "pk"),
            },
        ),
        migrations.CreateModel(
            name="ResearcherTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[("pt-br", "Português (Brasil)"), ("en", "English")],
                        max_length=5,
                        verbose_name="idioma",
                    ),
                ),
                ("slug", models.SlugField(blank=True, max_length=220, null=True)),
                ("role", models.CharField(blank=True, max_length=200, verbose_name="função")),
                (
                    "research_area",
                    models.CharField(blank=True, max_length=200, verbose_name="área de pesquisa"),
                ),
                ("biography_html", models.TextField(blank=True, verbose_name="biografia")),
                (
                    "photo_alt_text",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="texto alternativo da foto",
                    ),
                ),
                (
                    "seo_title",
                    models.CharField(blank=True, max_length=70, verbose_name="título para SEO"),
                ),
                (
                    "seo_description",
                    models.CharField(blank=True, max_length=160, verbose_name="descrição para SEO"),
                ),
                (
                    "researcher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="researchers.researcher",
                    ),
                ),
            ],
            options={
                "verbose_name": "tradução",
                "verbose_name_plural": "traduções",
                "ordering": ("language",),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("researcher", "language"),
                        name="unique_researcher_translation_language",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("slug__isnull", False)),
                        fields=("language", "slug"),
                        name="unique_researcher_translation_slug_per_language",
                    ),
                ],
            },
        ),
    ]
