# Generated by Django 5.2.17 on 2026-08-29 14:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("researchers", "0003_add_master_academic_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="researchertranslation",
            name="photo_alt_text",
        ),
        migrations.RemoveField(
            model_name="researchertranslation",
            name="role",
        ),
    ]
